import pandas as pd

In [2]:
studentvle = pd.read_csv("dataset/studentVle.csv")

studentvle.head(10)

In [4]:
studentvle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        object
 1   code_presentation  object
 2   id_student         int64
 3   id_site            int64
 4   date               int64
 5   sum_click          int64
dtypes: int64(4), object(2)
memory usage: 487.8+ MB

In [5]:
vle = pd.read_csv("dataset/vle.csv")

In [6]:
vle.head(10)

   id_site code_module code_presentation activity_type week_from week_to
0   546943         AAA             2013J      resource         ?       ?
1   546712         AAA             2013J     oucontent         ?       ?
2   546998         AAA             2013J      resource         ?       ?
3   546888         AAA             2013J           url         ?       ?
4   547035         AAA             2013J      resource         ?       ?
5   546614         AAA             2013J      homepage         ?       ?
6   546897         AAA             2013J           url         ?       ?
7   546678         AAA             2013J     oucontent         ?       ?
8   546933         AAA             2013J      resource         ?       ?
9   546708         AAA             2013J     oucontent         ?       ?

In [7]:
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_site            6364 non-null   int64
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
 4   week_from          6364 non-null   object
 5   week_to            6364 non-null   object
dtypes: int64(1), object(5)
memory usage: 298.4+ KB

In [8]:
studentreg = pd.read_csv("dataset/studentRegistration.csv")

In [9]:
studentreg.head(10)

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159,?
1,AAA,2013J,28400,-53,?
2,AAA,2013J,30268,-92,12
3,AAA,2013J,31604,-52,?
4,AAA,2013J,32885,-176,?
5,AAA,2013J,38053,-110,?
6,AAA,2013J,45462,-67,?
7,AAA,2013J,45642,-29,?
8,AAA,2013J,52130,-33,?
9,AAA,2013J,53025,-179,?

In [10]:
studentreg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   code_module          32593 non-null  object
 1   code_presentation    32593 non-null  object
 2   id_student           32593 non-null  int64
 3   date_registration    32593 non-null  object
 4   date_unregistration  32593 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.2+ MB

In [11]:
assessment = pd.read_csv("dataset/assessments.csv")

In [12]:
assessment.head(10)

  code_module code_presentation  id_assessment assessment_type date  weight
0         AAA             2013J           1752             TMA   19    10.0
1         AAA             2013J           1753             TMA   54    20.0
2         AAA             2013J           1754             TMA  117    20.0
3         AAA             2013J           1755             TMA  166    20.0
4         AAA             2013J           1756             TMA  215    30.0
5         AAA             2013J           1757            Exam    ?   100.0
6         AAA             2014J           1758             TMA   19    10.0
7         AAA             2014J           1759             TMA   54    20.0
8         AAA             2014J           1760             TMA  117    20.0
9         AAA             2014J           1761             TMA  166    20.0

In [13]:
assessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        206 non-null    object
 1   code_presentation  206 non-null    object
 2   id_assessment      206 non-null    int64
 3   assessment_type    206 non-null    object
 4   date               206 non-null    object
 5   weight             206 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 9.8+ KB

In [14]:
courses = pd.read_csv("dataset/courses.csv")

In [15]:
courses.head(10)

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240
5         BBB             2014B                         234
6         CCC             2014J                         269
7         CCC             2014B                         241
8         DDD             2013J                         261
9         DDD             2014J                         262

In [16]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 22 non-null     object
 1   code_presentation           22 non-null     object
 2   module_presentation_length  22 non-null     int64
dtypes: int64(1), object(2)
memory usage: 660.0+ bytes

In [17]:
studentasses = pd.read_csv("dataset/studentAssessment.csv")

In [18]:
studentasses.head(10)

   id_assessment  id_student  date_submitted  is_banked score
0           1752       11391              18          0    78
1           1752       28400              22          0    70
2           1752       31604              17          0    72
3           1752       32885              26          0    69
4           1752       38053              19          0    79
5           1752       45462              20          0    70
6           1752       45642              18          0    72
7           1752       52130              19          0    72
8           1752       53025               9          0    71
9           1752       57506              18          0    68

In [19]:
studentasses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_assessment   173912 non-null  int64
 1   id_student      173912 non-null  int64
 2   date_submitted  173912 non-null  int64
 3   is_banked       173912 non-null  int64
 4   score           173912 non-null  object
dtypes: int64(4), object(1)
memory usage: 6.6+ MB

In [20]:
studentinfo = pd.read_csv("dataset/studentInfo.csv")

In [21]:
studentinfo.head(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass
5,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,N,Pass
6,AAA,2013J,45462,M,Scotland,HE Qualification,30-40%,0-35,0,60,N,Pass
7,AAA,2013J,45642,F,North Western Region,A Level or Equivalent,90-100%,0-35,0,120,N,Pass
8,AAA,2013J,52130,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,90,N,Pass
9,AAA,2013J,53025,M,North Region,Post Graduate Qualification,?,55<=,0,60,N,Pass

In [22]:
studentinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              32593 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB

In [23]:
# from here we start to join all dataset

In [24]:
df_student = pd.merge(
    studentinfo,
    studentreg,
    on=["code_module", "code_presentation", "id_student"],
    how="left"
)

In [25]:
df_student.head(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,-159,?
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,-53,?
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,-92,12
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,-52,?
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,-176,?
5,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,N,Pass,-110,?
6,AAA,2013J,45462,M,Scotland,HE Qualification,30-40%,0-35,0,60,N,Pass,-67,?
7,AAA,2013J,45642,F,North Western Region,A Level or Equivalent,90-100%,0-35,0,120,N,Pass,-29,?
8,AAA,2013J,52130,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,90,N,Pass,-33,?
9,AAA,2013J,53025,M,North Region,Post Graduate Qualification,?,55<=,0,60,N,Pass,-179,?

In [26]:
df_student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              32593 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
 12  date_registration     32593 non-null  object
 13  date_unregistration   32593 non-null  object
dtypes: int64(3), object(11)
memory usage: 3.5+ MB

In [27]:
df_student = pd.merge(
    df_student,
    courses,
    on=["code_module", "code_presentation"],
    how="left"
)

In [28]:
df_student.head(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,-159,?,268
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,-53,?,268
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,-92,12,268
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,-52,?,268
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,-176,?,268
5,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,N,Pass,-110,?,268
6,AAA,2013J,45462,M,Scotland,HE Qualification,30-40%,0-35,0,60,N,Pass,-67,?,268
7,AAA,2013J,45642,F,North Western Region,A Level or Equivalent,90-100%,0-35,0,120,N,Pass,-29,?,268
8,AAA,2013J,52130,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,90,N,Pass,-33,?,268
9,AAA,2013J,53025,M,North Region,Post Graduate Qualification,?,55<=,0,60,N,Pass,-179,?,268

In [29]:
df_student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 32593 non-null  object
 1   code_presentation           32593 non-null  object
 2   id_student                  32593 non-null  int64
 3   gender                      32593 non-null  object
 4   region                      32593 non-null  object
 5   highest_education           32593 non-null  object
 6   imd_band                    32593 non-null  object
 7   age_band                    32593 non-null  object
 8   num_of_prev_attempts        32593 non-null  int64
 9   studied_credits             32593 non-null  int64
 10  disability                  32593 non-null  object
 11  final_result                32593 non-null  object
 12  date_registration           32593 non-null  object
 13  date_unregistration         32593 non-null  object
 14  module_presentation_length  32593 non-null  int64
dtypes: int64(4), object(11)
memory usage: 3.7+ MB

In [30]:
df_assessment = pd.merge(
    studentasses,
    assessment,
    on="id_assessment",
    how="left"
)

In [31]:
df_assessment.head(10)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight
0,1752,11391,18,0,78,AAA,2013J,TMA,19,10.0
1,1752,28400,22,0,70,AAA,2013J,TMA,19,10.0
2,1752,31604,17,0,72,AAA,2013J,TMA,19,10.0
3,1752,32885,26,0,69,AAA,2013J,TMA,19,10.0
4,1752,38053,19,0,79,AAA,2013J,TMA,19,10.0
5,1752,45462,20,0,70,AAA,2013J,TMA,19,10.0
6,1752,45642,18,0,72,AAA,2013J,TMA,19,10.0
7,1752,52130,19,0,72,AAA,2013J,TMA,19,10.0
8,1752,53025,9,0,71,AAA,2013J,TMA,19,10.0
9,1752,57506,18,0,68,AAA,2013J,TMA,19,10.0

In [32]:
df_assessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id_assessment      173912 non-null  int64
 1   id_student         173912 non-null  int64
 2   date_submitted     173912 non-null  int64
 3   is_banked          173912 non-null  int64
 4   score              173912 non-null  object
 5   code_module        173912 non-null  object
 6   code_presentation  173912 non-null  object
 7   assessment_type    173912 non-null  object
 8   date               173912 non-null  object
 9   weight             173912 non-null  float64
dtypes: float64(1), int64(4), object(5)
memory usage: 13.3+ MB

In [33]:
df_student = pd.merge(
    df_student,
    df_assessment,
    on=["id_student", "code_module", "code_presentation"],
    how="left"
)

In [34]:
df_student.head(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,date_registration,date_unregistration,module_presentation_length,id_assessment,date_submitted,is_banked,score,assessment_type,date,weight
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,-159,?,268,1752.0,18.0,0.0,78,TMA,19,10.0
1,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,-159,?,268,1753.0,53.0,0.0,85,TMA,54,20.0
2,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,-159,?,268,1754.0,115.0,0.0,80,TMA,117,20.0
3,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,-159,?,268,1755.0,164.0,0.0,85,TMA,166,20.0
4,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,-159,?,268,1756.0,212.0,0.0,82,TMA,215,30.0
5,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,-53,?,268,1752.0,22.0,0.0,70,TMA,19,10.0
6,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,-53,?,268,1753.0,52.0,0.0,68,TMA,54,20.0
7,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,-53,?,268,1754.0,121.0,0.0,70,TMA,117,20.0
8,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,-53,?,268,1755.0,164.0,0.0,64,TMA,166,20.0
9,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,-53,?,268,1756.0,212.0,0.0,60,TMA,215,30.0

In [35]:
df_student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180662 entries, 0 to 180661
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   code_module                 180662 non-null  object
 1   code_presentation           180662 non-null  object
 2   id_student                  180662 non-null  int64
 3   gender                      180662 non-null  object
 4   region                      180662 non-null  object
 5   highest_education           180662 non-null  object
 6   imd_band                    180662 non-null  object
 7   age_band                    180662 non-null  object
 8   num_of_prev_attempts        180662 non-null  int64
 9   studied_credits             180662 non-null  int64
 10  disability                  180662 non-null  object
 11  final_result                180662 non-null  object
 12  date_registration           180662 non-null  object
 13  date_unregistration         180662 non-null  object
 14  module_presentation_length  180662 non-null  int64
 15  id_assessment               173912 non-null  float64
 16  date_submitted              173912 non-null  float64
 17  is_banked                   173912 non-null  float64
 18  score                       173912 non-null  object
 19  assessment_type             173912 non-null  object
 20  date                        173912 non-null  object
 21  weight                      173912 non-null  float64
dtypes: float64(4), int64(4), object(14)
memory usage: 30.3+ MB

In [36]:
df_vle = pd.merge(
    studentvle,
    vle,
    on=["id_site", "code_module", "code_presentation"],
    how="left"
)

In [37]:
df_vle.head(10)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,week_from,week_to
0,AAA,2013J,28400,546652,-10,4,forumng,?,?
1,AAA,2013J,28400,546652,-10,1,forumng,?,?
2,AAA,2013J,28400,546652,-10,1,forumng,?,?
3,AAA,2013J,28400,546614,-10,11,homepage,?,?
4,AAA,2013J,28400,546714,-10,1,oucontent,?,?
5,AAA,2013J,28400,546652,-10,8,forumng,?,?
6,AAA,2013J,28400,546876,-10,2,subpage,?,?
7,AAA,2013J,28400,546688,-10,15,oucontent,?,?
8,AAA,2013J,28400,546662,-10,17,oucontent,?,?
9,AAA,2013J,28400,546890,-10,1,url,?,?

In [38]:
df_vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        object
 1   code_presentation  object
 2   id_student         int64
 3   id_site            int64
 4   date               int64
 5   sum_click          int64
 6   activity_type      object
 7   week_from          object
 8   week_to            object
dtypes: int64(4), object(5)
memory usage: 731.6+ MB

In [40]:
vle_agg = (
    studentvle
    .groupby(["code_module", "code_presentation", "id_student"])
    ["sum_click"]
    .sum()
    .reset_index()
)

In [41]:
df_student = pd.merge(
    df_student,
    vle_agg,
    on=["code_module", "code_presentation", "id_student"],
    how="left"
)

In [42]:
df_student.head(10)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,...,date_unregistration,module_presentation_length,id_assessment,date_submitted,is_banked,score,assessment_type,date,weight,sum_click
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,?,268,1752.0,18.0,0.0,78,TMA,19,10.0,934.0
1,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,?,268,1753.0,53.0,0.0,85,TMA,54,20.0,934.0
2,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,?,268,1754.0,115.0,0.0,80,TMA,117,20.0,934.0
3,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,?,268,1755.0,164.0,0.0,85,TMA,166,20.0,934.0
4,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,...,?,268,1756.0,212.0,0.0,82,TMA,215,30.0,934.0
5,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,?,268,1752.0,22.0,0.0,70,TMA,19,10.0,1435.0
6,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,?,268,1753.0,52.0,0.0,68,TMA,54,20.0,1435.0
7,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,?,268,1754.0,121.0,0.0,70,TMA,117,20.0,1435.0
8,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,?,268,1755.0,164.0,0.0,64,TMA,166,20.0,1435.0
9,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,...,?,268,1756.0,212.0,0.0,60,TMA,215,30.0,1435.0

In [43]:
df_student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180662 entries, 0 to 180661
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   code_module                 180662 non-null  object
 1   code_presentation           180662 non-null  object
 2   id_student                  180662 non-null  int64
 3   gender                      180662 non-null  object
 4   region                      180662 non-null  object
 5   highest_education           180662 non-null  object
 6   imd_band                    180662 non-null  object
 7   age_band                    180662 non-null  object
 8   num_of_prev_attempts        180662 non-null  int64
 9   studied_credits             180662 non-null  int64
 10  disability                  180662 non-null  object
 11  final_result                180662 non-null  object
 12  date_registration           180662 non-null  object
 13  date_unregistration         180662 non-null  object
 14  module_presentation_length  180662 non-null  int64
 15  id_assessment               173912 non-null  float64
 16  date_submitted              173912 non-null  float64
 17  is_banked                   173912 non-null  float64
 18  score                       173912 non-null  object
 19  assessment_type             173912 non-null  object
 20  date                        173912 non-null  object
 21  weight                      173912 non-null  float64
 22  sum_click                   177179 non-null  float64
dtypes: float64(5), int64(4), object(14)
memory usage: 31.7+ MB

In [47]:
df_student.to_excel("student_dataset.xlsx")